# Generated by Django 3.2.23 on 2024-02-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=90)),
                ('contact', models.IntegerField()),
                ('address', models.TextField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
